### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by gja876** [creepymonster/nightscout-to-libreview#9]
Hi, I got this error both on my mac and windows, can you have a look what is wrong? Passwords are 100% correct, I also set true to recreate your device id

`C:\Users\Gustaw\nightscout-to-libreview\node_modules\axios\lib\core\createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 401
    at createError (C:\Users\Gustaw\nightscout-to-libreview\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Gustaw\nightscout-to-libreview\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Gustaw\nightscout-to-libreview\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    url: 'https://gut5.10be.de/api/v1/entries.json?find[dateString][$gte]=2024-01-01&find[dateString][$lte]=2024-02-01&count=131072&token=XXXXX',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4'
    },`

**Comment by gja876** [comment]
I was using password instead of token

**Comment by Jagieuu** [comment]
Hey could you help me? in cmd in line
please enter your Nightscout token: should I write the password that I use to log in to the admin on the nightscout website? Should I create a role?
@gja876
